from .create_markdown_image import (
    NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_MARKDOWN,
    NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_MARKDOWN
)
from .create_dialog_image import (
    NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_DIALOG,
    NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_DIALOG
)
from .create_dialog_image_v2 import (
    NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_DIALOG_V2,
    NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_DIALOG_V2
)

NODE_CLASS_MAPPINGS = {**NODE_CLASS_MAPPINGS_MARKDOWN, **NODE_CLASS_MAPPINGS_DIALOG, **NODE_CLASS_MAPPINGS_DIALOG_V2}
NODE_DISPLAY_NAME_MAPPINGS = {**NODE_DISPLAY_NAME_MAPPINGS_MARKDOWN, **NODE_DISPLAY_NAME_MAPPINGS_DIALOG, **NODE_DISPLAY_NAME_MAPPINGS_DIALOG_V2}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
