from .create_markdown_image import (
    NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_MARKDOWN,
    NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_MARKDOWN
)
from .create_dialog_image import (
    NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_DIALOG,
    NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_DIALOG
)

NODE_CLASS_MAPPINGS = {**NODE_CLASS_MAPPINGS_MARKDOWN, **NODE_CLASS_MAPPINGS_DIALOG}
NODE_DISPLAY_NAME_MAPPINGS = {**NODE_DISPLAY_NAME_MAPPINGS_MARKDOWN, **NODE_DISPLAY_NAME_MAPPINGS_DIALOG}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
